# Generated by Django 2.2.12 on 2023-10-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='questionId',
            field=models.IntegerField(default=1, verbose_name='关联问题id'),
            preserve_default=False,
        ),
    ]
